### PR TITLE
changed formatting on all files to comply with variable assignment pr…

### PR DESCRIPTION
**Pull request by Greg-Mah**
…actices

### CODE REVIEW

**Review by stickslammer — APPROVED** [review]
I concur

**Review by stickslammer — DISMISSED** [review]
Look good

**Review by Ryantran4 — COMMENTED** [review]
looks good

**Review by Ryantran4 — COMMENTED** [review]
thanks

**Review by Ryantran4 — APPROVED** [review]
thanks for fixes

**Pull request merged**
